trigger:
  branches:
    include:
    - master
    - validate/*
    - release/*
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  $15aa7de16-60fb-4dd0-a737-8cbfca48115b
  ci_feed: /e08c98c0-63d6-4dc6-80ca-944e4deaf3d2

jobs:
- template: azure-pipelines/build.yml
